### ISSUE TITLE
Broken // Well this is akward on startup.

### ISSUE THREAD

**Issue by Masono03** [Echological/LinkBanner-BD#1]
As the title says. 
Canary 139699 (bdc9502)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by Setloth** [comment]
Since I do not actively have Canary installed, or your windows version, could you please provide more information, like, a copy of the error that occurs on startup?

**Comment by Masono03** [comment]
it literally just gives a failed to constrcut at start and gets that screen stuck. i had to delete it from the folder to even get discord to start to where i can even acess the console :/

**Comment by Setloth** [comment]
the console should be able to be opened when discord isnt even finished loading... you can open it as soon as the main window starts

Make sure you have DevTools enabled in the BD settings, then once you do, you can just hit ctrl+shift+i and see the console. 

Since I am not sure of the issue with the plugin starting on canary, I will need a more detailed stack trace to be able to work on this.

**Comment by Masono03** [comment]
so downloaded it again and cheked console and nothing just the failed the construct but doesnt show anything in the console when it starts back up

**Comment by Setloth** [comment]
Odd. And no error from BD or any modal popup? if there is one, could you please send, I am interested to know more.

**Comment by Masono03** [comment]
nope nothing tho there was a update inbetween when this first happened and now so i dunno if there was another canary patch that messed with stuff plus theres even a third one that i didnt download yet....canary had like 5 patches today

**Comment by Setloth** [comment]
interesting, I am quite unsure... 

if you run:
```js
document.addEventListener("click", ({target}) => {
    if (target.style.backgroundImage && target.style.backgroundImage.includes("banner")) console.log(target.style.backgroundImage.substring(4,target.style.backgroundImage.length-1).replace(/["']/g, ""))

})
```

in the console, does it give an error? and if not, does it log anything when you click on a banner?

**Comment by Masono03** [comment]
so i just let the current update go through on canary and now the plugin seems to work again? honestly i lost track of whats going on with discord since yesterday...

**Comment by Setloth** [comment]
lol i have no idea... if its working, that's good i guess
